#!/usr/bin/env bash
# A script that looks up DNS records of a passed domain
lookup (){
    dig +noall +answer "$1" | 
        awk '
        {split($1,a,"."); 
        printf "The subdomain %s is a %s record and points to %s\n", a[1], $4, $5 }
        '
}



if [ "$#" -eq 1 ];
then
    lookup "www.$1"
    lookup "lb-01.$1"
    lookup "web-01.$1"
    lookup "web-02.$1"
elif [ "$#" -eq 2 ];
then
    lookup "$2.$1"
fi
