#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt update
sudo apt -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
