#!/usr/bin/env bash
# installs nginx on the server and Configures  4-not_found_page_404

REDIRECT="\\\\n\tlocation / redirect_me {\n\t\t return 301 https://www.youtube.com;\n\t}"
NOT_FOUND="\\\n\t\terror_page 404 /404.html;"
File="/var/www/html/index.html"
