#!/usr/bin/env bash
# Configure Nginx to add a custom HTTP header

# Update packages
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Add custom HTTP header configuration to Nginx
echo '
server {
    add_header X-Served-By $hostname;
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/html;
    index index.html index.htm;
}
' | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

