#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# Update the package list and install nginx
sudo apt-get -y update
sudo apt install -y nginx

custom_header="add_header X-Served-By \$hostname;"

sudo sed -i "/http {/a \ \ \ \ $custom_header" /etc/nginx/nginx.conf

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

NEW_RULE="\\\a\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/@tboy54321;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
