#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01

# get updates
sudo apt-get -y update

# install ufw firewall
sudo apt-get -y install ufw

# enable ufw
sudo ufw enable

# set default rules
sudo ufw default deny incoming
sudo ufw default allow outgoing

# allow port 22(ssh), 443(https ssl), 80(http)

# Allow SSH (port 22)
sudo ufw allow 22/tcp
# Allow HTTPS (port 443)
sudo ufw allow 443/tcp
# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# check ufw status, use sudo ufw status verbose for more details
sudo ufw status

