#!/usr/bin/env bash
# make nginx to run as nginx user
sed -i "s/# user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/\b80\b/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start

